[workspace]
members = ["crates/ting-server", "crates/ting-client", "crates/ting-cli", "crates/ting-daemon"]
exclude = ["vendor/silicon-iam-client"]
resolver = "2"

[workspace.package]
version = "0.1.8"
edition = "2024"
license = "MIT"
repository = "https://github.com/teamofsilicons/silicon-ting"

[profile.release]
lto = "thin"
strip = true
