[package]
name = "silicon-ting-cli"
version = "0.1.4"
edition = "2024"
description = "Ting command-line client"
license = "MIT"
repository = "https://github.com/teamofsilicons/silicon-ting"
homepage = "https://ting.teamofsilicons.com"
readme = "../../README.md"
[[bin]]
name = "ting"
path = "src/main.rs"
[dependencies]
silicon-ting-client = { path = "../ting-client", version = "0.1.4" }
clap = { version = "4", features = ["string"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["v4"] }
base64 = "0.22"
